#!/bin/bash

./mill mill.scalalib.PublishModule/publishAll \
    --sonatypeUri https://maven.pkg.github.com/markarasev/simplesql \
    --sonatypeCreds markarasev:$GITHUB_TOKEN\
    --signed false \
    --publishArtifacts __.publishArtifacts \
    --stagingRelease false
