#!/bin/bash

./mill mill.javalib.MavenPublishModule/ \
    --releaseUri https://maven.pkg.github.com/markarasev/simplesql \
    --snapshotUri https://maven.pkg.github.com/markarasev/simplesql \
    --username markarasev \
    --password $GITHUB_TOKEN
